development:
  adapter: postgresql
  encoding: utf8
  database: rails_sample_app_test
  pool: 5
  username: postgres
  password: fuckyou

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rails_sample_app_test
  pool: 5
  username: postgres
  password: fuckyou

production:
  adapter: postgresql
  encoding: utf8
  database: rails_sample_app_production
  pool: 5
  username: 
  password: